#!/usr/bin/env python3
"""Emit an ngspice netlist for the FS-3W power amplifier core.

The element cards are generated from tools/channel_netlist.py, which is the same
data that will generate the KiCad schematic. That is the point: the circuit that
gets simulated is provably the circuit that gets built, rather than a hand-typed
approximation of it that drifts.

Scope: the power amplifier stage, from AIN to SPK_OUT. The input receiver and
gain trim (U1, R1, R2, R7, C1-C5, R3, RV1, C6) are omitted and replaced by a
drive source in the analysis deck -- an INA165x contributes -120 dB THD and has
no bearing on loop stability.

The feedback divider node (FB) and the LTP feedback base (Q1B_B) are emitted
UNCONNECTED. Each analysis deck joins them: with a 0 V source for closed-loop
operation (a milliohm resistor will not solve at 2 ohm -- see docs/02 §2.6),
or with a 100 kH inductor plus an injection source to open the loop for
gain/phase measurement.

    python3 tools/gen_spice.py -o sim/channel_core.net
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from channel_netlist import COMPONENTS, NETLIST  # noqa: E402

# Sections replaced by the analysis deck's drive source.
OMIT_REFS = {"R1", "R2", "R7", "U1", "C1", "C2", "C3", "C4", "C5",
             "R3", "RV1", "C6", "R5", "Q16"}

# Ground nets collapse to SPICE node 0.
GROUND_NETS = {"SIG_GND", "PWR_GND"}

# Rail nets and their voltages.
RAILS = {
    "VCC_MAIN": 24.0, "VEE_MAIN": -24.0,
    "VCC_FE": 30.0, "VEE_FE": -30.0,
    "VCC_15": 15.0, "VEE_15": -15.0,
}

# Sense outputs that would otherwise float.
TERMINATE_1G = {"DC_SENSE", "I_SENSE"}

# Loop break. Q1B's base is on FB in the real circuit; here it gets its own node
# so the analysis deck decides how the two are joined.
SPLIT_PIN_NET = {("Q1B", "B"): "Q1B_B"}

# Emitted as {r21}/{r22} rather than as literals, so the bias sweeps can override
# them at parse time. Defaults still come from channel_netlist.py; this is only the
# set of refs that get the treatment.
PARAM_RESISTORS = ("R21", "R22")

MODEL_MAP = {
    "NJW0281G": "QNJW0281", "NJW0302G": "QNJW0302",
    "MJE15032": "QMJE15032", "MJE15033": "QMJE15033",
    "TTC004B": "QTTC004B", "TTA004B": "QTTA004B",
    "BC847C": "QBC847C", "BC857C": "QBC857C",
    "BCM847BS": "QBC847C", "BCM857BS": "QBC857C",
    "LED_RED": "DLEDRED", "BZX84C5V1": "DZ5V1",
}

MULT = {"R": 1.0, "k": 1e3, "M": 1e6,
        "p": 1e-12, "n": 1e-9, "u": 1e-6, "m": 1e-3}

# Bias trimmer: total track and the setpoint that gives 45 mA per output device.
# Re-derive with `python3 tools/sim_sweep.py verify` after any change to the
# spreader, the output stage or the device models.
RV2_TRACK = 100.0
RV2_SETPOINT = 47.0


def parse_value(text: str) -> float:
    """'2k2'->2200, '0R22'->0.22, '2u2'->2.2e-6, '100n/100V'->1e-7."""
    s = text.split("/")[0].strip()
    if s.startswith("0R link") or s == "0R":
        return 1e-3
    m = re.fullmatch(r"(\d*)([RkMpnum])(\d*)", s)
    if m:
        head, letter, tail = m.groups()
        num = float(f"{head or 0}.{tail}") if tail else float(head)
        return num * MULT[letter]
    m = re.fullmatch(r"([\d.]+)\s*([RkMpnum])?", s)
    if m:
        num = float(m.group(1))
        return num * MULT.get(m.group(2) or "R", 1.0)
    raise ValueError(f"cannot parse value {text!r}")


def build(model_overrides: dict[str, str] | None = None) -> list[str]:
    model_overrides = model_overrides or {}
    by_ref = {c.ref: c for c in COMPONENTS}
    conn: dict[tuple[str, str], str] = {}
    for ref, pin, net in NETLIST:
        conn[(ref, pin)] = net

    def node(ref: str, pin: str) -> str:
        net = SPLIT_PIN_NET.get((ref, pin), conn[(ref, pin)])
        return "0" if net in GROUND_NETS else net

    out: list[str] = []
    e = out.append

    e("* FS-3W amplifier channel core -- GENERATED by tools/gen_spice.py")
    e("* Do not edit. Change tools/channel_netlist.py and regenerate.")
    e("*")
    e("* FB and Q1B_B are intentionally left unconnected; the analysis deck")
    e("* joins them. See tools/gen_spice.py docstring.")
    e("*")
    e("* Bias trimmer position: rv2_b is the ohms of RV2's track left in the")
    e("* multiplier's lower leg, so it is valid over 0..RV2 and nothing else.")
    e("* The default is the setpoint found by tools/sim_sweep.py verify, which is")
    e("* 45 mA per output device. Setting it outside the track range biases the")
    e("* output stage off, and an AC analysis will then report a stable-looking")
    e("* amplifier that is really just a dead one, so the decks re-check Iq.")
    e(f".param rv2_a={RV2_TRACK - RV2_SETPOINT:g} rv2_b={RV2_SETPOINT:g}")
    e("*")
    e("* Device temperatures. t_hs applies to everything bolted to the main")
    e("* heatsink (Q7 Q10-Q15), t_pcb to everything else. Sweeping them")
    e("* independently is how the bias spreader's tracking gets verified.")
    e(".param t_hs=25 t_pcb=25")
    e("*")
    e("* Bias spreader divider legs, as parameters rather than literals so a")
    e("* sweep can override them with a second .param instead of `alter`. That")
    e("* is not cosmetic: `alter` on these two resistors leaves the solver in a")
    e("* state from which it reaches the spurious collapsed-spreader operating")
    e("* point at heatsink temperatures near 55 C, where a parse-time override")
    e("* converges on the real one. See tools/sim_sweep.py.")
    by_ref = {c.ref: c for c in COMPONENTS}
    e(".param " + " ".join(
        f"{r.lower()}={parse_value(by_ref[r].value):g}" for r in PARAM_RESISTORS))
    e("")
    e("* ---- rails ----")
    for net, v in RAILS.items():
        e(f"V{net} {net} 0 DC {v}")
    e("")

    skipped, emitted = [], 0
    sections: dict[str, list[str]] = {}

    for c in COMPONENTS:
        if c.ref in OMIT_REFS or c.dnp or c.ref == "U2P":
            skipped.append(c.ref)
            continue

        kind = re.match(r"[A-Z]+", c.ref).group(0)
        cards: list[str] = []

        if kind == "R":
            val = (f"{{{c.ref.lower()}}}" if c.ref in PARAM_RESISTORS
                   else f"{parse_value(c.value):g}")
            cards.append(f"R{c.ref} {node(c.ref,'1')} {node(c.ref,'2')} {val}")
        elif kind == "C":
            cards.append(f"C{c.ref} {node(c.ref,'1')} {node(c.ref,'2')} "
                         f"{parse_value(c.value):g}")
        elif kind == "L":
            cards.append(f"L{c.ref} {node(c.ref,'1')} {node(c.ref,'2')} "
                         f"{parse_value(c.value):g}")
        elif kind == "RV":
            # The wiper splits the track into two resistors. If the wiper is
            # strapped to an end pin, that section is shorted out and only the
            # other one is emitted -- a resistor with both nodes on the same net
            # is a singularity SPICE has no reason to enjoy.
            n1, n2, n3 = (node(c.ref, p) for p in ("1", "2", "3"))
            if n1 != n2:
                cards.append(f"R{c.ref}A {n1} {n2} {{{c.ref.lower()}_a}}")
            if n2 != n3:
                cards.append(f"R{c.ref}B {n2} {n3} {{{c.ref.lower()}_b}}")
        elif kind == "Q":
            # Per-instance temperature, tied to where the device physically sits.
            # This is what makes the thermal-tracking claim testable: heat the
            # heatsink group and watch what the bias spreader does about it.
            tnode = "t_hs" if c.on_heatsink else "t_pcb"
            model = model_overrides.get(c.ref, MODEL_MAP[c.value])
            cards.append(f"Q{c.ref} {node(c.ref,'C')} {node(c.ref,'B')} "
                         f"{node(c.ref,'E')} {model} temp={{{tnode}}}")
        elif kind == "D":
            # SPICE diode order is anode then cathode
            cards.append(f"D{c.ref} {node(c.ref,'A')} {node(c.ref,'K')} "
                         f"{MODEL_MAP[c.value]}")
        elif kind == "U":
            cards.append(f"X{c.ref} {node(c.ref,'IN+')} {node(c.ref,'IN-')} "
                         f"{node(c.ref,'OUT')} VCC_15 VEE_15 OPA1642")
        else:
            raise ValueError(f"no SPICE mapping for {c.ref}")

        sections.setdefault(c.desc.split(",")[0] or "misc", []).extend(cards)
        emitted += len(cards)

    for title, cards in sections.items():
        e(f"* ---- {title} ----")
        out.extend(cards)
        e("")

    e("* ---- terminations for otherwise floating sense outputs ----")
    for net in sorted(TERMINATE_1G):
        e(f"Rterm_{net} {net} 0 1G")
    e("")
    e(f"* {emitted} element cards emitted; "
      f"{len(skipped)} refs omitted ({', '.join(sorted(skipped))})")
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("-o", "--out", default="sim/channel_core.net")
    p.add_argument("--model", action="append", default=[], metavar="REF=MODEL",
                   help="override one device's SPICE model, e.g. Q7=QNJW0281. "
                        "Used for the Q7 die-size study; see docs/02 2.3.")
    a = p.parse_args()
    overrides = dict(kv.split("=", 1) for kv in a.model)
    lines = build(overrides)
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {a.out}: {len(lines)} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
